### ISSUE TITLE
Upgrading from Alpha 2 to Alpha 3 results in crash

### ISSUE THREAD

**Issue by Routhinator** [elytra/Correlated#54]
```
Could not find a DimensionType by id: correlatedpotentialistics:limbo
```

Minecraft: 1.10.2

Full Trace:
```
[00:58:49] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: derp
	at net.minecraft.world.storage.SaveHandler.redirect$onLoadWorldInfo$zon000(SaveHandler.java:69) ~[azy.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:121) ~[azy.class:?]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:699) ~[WorldManager.class:1.10.2-2171-5.1.0-BETA-1973]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:330) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalArgumentException: Could not find a DimensionType by id: correlatedpotentialistics:limbo
	at org.spongepowered.common.util.FunctionalUtil.lambda$invalidArgument$0(FunctionalUtil.java:32) ~[FunctionalUtil.class:1.10.2-2171-5.1.0-BETA-1973]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_112]
	at net.minecraft.world.storage.WorldInfo.readSpongeNbt(WorldInfo.java:732) ~[baa.class:?]
	at net.minecraft.world.storage.SaveHandler.loadSpongeDatData(SaveHandler.java:115) ~[azy.class:?]
	at net.minecraft.world.storage.SaveHandler.redirect$onLoadWorldInfo$zon000(SaveHandler.java:67) ~[azy.class:?]
	... 6 more

```

**Comment by unascribed** [comment]
This is a Sponge issue. There's not really a good way to fix this on my end.

**Comment by Routhinator** [comment]
Is there a way to make it so I can use the mod again in our world or are we just going without now?

**Comment by unascribed** [comment]
Try deleting the DIM folder for the CoPo dungeon, since it's not used yet. The default ID is -31, check your config. If it's -31 the folder will be world/DIM-31.

**Comment by Routhinator** [comment]
That seems to have gotten it. Looking forward to testing Alpha3 - thanks.
