### ISSUE TITLE
Crash when loading on server side, 1.12

### ISSUE THREAD

**Issue by asiekierka** [elytra/Correlated#75]
java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_31]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2693) ~[?:1.8.0_31]
        at java.lang.Class.privateGetPublicMethods(Class.java:2894) ~[?:1.8.0_31]
        at java.lang.Class.getMethods(Class.java:1607) ~[?:1.8.0_31]
        at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81) [EventBus.class:?]
        at com.elytradev.correlated.item.ItemWeldthrower.<init>(ItemWeldthrower.java:39) ~[ItemWeldthrower.class:?]
        at com.elytradev.correlated.init.CItems.register(CItems.java:47) ~[CItems.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_288_CItems_register_Register.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143) ~[EventBus$1.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:726) [GameData.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:605) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
        ... 18 more

Latest Jenkins build

**Comment by unascribed** [comment]
VER YGOO DJOB
